为TrackRoute增加HOC
otakustay/react-track pull request #3
Opened 2018-06-15 06:33 UTC by hy-pillow

为TrackRoute增加HOC，在demo中使用AboutMe组件测试

2018-06-16 06:50 UTC, otakustay requested changes
另外trackEvent也希望有hoc版本哦

2018-06-16 06:50 UTC, otakustay commented on src/hoc/index.js
> +export trackPageView from './trackPageView';
这个目录叫hocs吧，统一用复数

2018-06-16 06:50 UTC, otakustay commented on src/hoc/trackPageView.js
> +class TrackPageView extends Component {
这里应该能直接复用components下的TrackPageView

2018-06-18 06:30 UTC, hy-pillow commented
trackEvent看了一下，感觉不是很适合使用HOC的方式，因为需要给具体的元素上绑定事件。
如果直接给子组件外面包一层元素的话，会破坏原有的dom结构、层级
如果让子组件支持传入的事件，会让接入的成本提高很多

2018-06-19 02:44 UTC, otakustay commented
> trackEvent看了一下，感觉不是很适合使用HOC的方式，因为需要给具体的元素上绑定事件。

我们会有这样的需求

第一种情况是，我们正在实现一个组件，需要追踪这个组件的某个事件，而不仅仅是DOM：

```jsx
import {Select} from 'antd';

const CustomForm = ({onTypeChange}) => (
    <div>
        ...
        <Select onChange={onTypeChange}>
            ...
        </Select>
    </div>
);

export default trackEvent('form', 'change', 'type')(CustomForm);
```

另一种情况是，我们需要关注DOM上的事件，此时也同样可以用：

```jsx
const NameInput = trackEvent('form', 'change', 'name')('input');

export default ({onNameChange}) => (
    <div>
        ...
        {/* 与input一样使用 */}
        <NameInput onChange={onNameChange} />
    </div>
);
```

2018-06-19 02:53 UTC, otakustay requested changes
我的想法是这样：

- `TrackPageView`自带`withRouter`和`<Consumer>`，拿到路由相关的属性来加一些逻辑，然后继续渲染`children`，本身不需要干扰 `children`的功能（这样也不需要`omit`之类的逻辑了）
- `trackPageView(View)`等效于`<TrackPageView><View /></TrackPageView>`，不需要去控制`<Consumer>`等

2018-06-19 02:53 UTC, otakustay commented on src/components/TrackPageView.js
> -export default withRouter(TrackPageView);
这个不能从这里删除，因为你不确定使用了`trackPageView`的组件是不是一定放在`<Route>`下，也可能套了几层`match`和`params`已经不见了。为了保证一定能拿到这些属性，这里还是需要`withRouter`的

2018-06-19 02:53 UTC, otakustay commented on src/components/TrackPageView.js
> +        return <ComponentIn {...childProps} />;
感觉原来这里用`Route`是有问题的（都已经套了`withRouter`了），而`ComponentIn`也同样有问题，此处用`children`是不是更符合react的哲学

2018-06-19 02:53 UTC, otakustay commented on src/components/TrackPageView.js
暴露出去的同时补一下`propTypes`

2018-06-20 12:04 UTC, hy-pillow commented
对于：<TrackPageView><View /></TrackPageView>
TrackRoute我还保留了，使用时为<TrackRoute><View /></TrackRoute>
没有想到怎么把Consumer和withRouter写到一个组件中
如果有方式可以做到，我再改。

2018-06-21 03:35 UTC, otakustay commented
有点和我想的不一样，我希望我们有2种用法。

第一种，与`<Route>`组件完全兼容，包括以下几种：

```js
<TrackRoute path="/foo/:bar" component={MyView} />
<TrackRoute path="/foo/:bar">
    <MyView />
</TrackRoute>
<TrackRoute path="/foo/:bar" render={() => <MyView />} />
```

第二种，由`MyView`自行决定自己需要记录PV，可用在任何场景，不局限于在`<Route>`下：

```js
// MyView/index.js
export default trackPageView(MyView);

// Home.js
<Route path="/foo/:bar">
    <div>
        <header>
            My Home
        </header>
        <aside>
            Sidebar
        </aside>
        <main>
            <MyView />
        </main>
    </div>
</Route>
```

注意因为嵌套了好几层，所以`MyView`是拿不到路由信息的，需要`trackPageView`来处理。

---

基于这样的使用方法，我们需要3个东西：

第一是`TrackPageView`组件，它的作用就是拿到路由参数并发日志出去，接收`children`属性，它的`render`方法是简单的`return children;`

为了能拿到路由参数，`TrackPageView`自身是带了`withRouter`的，即最后在react上的结构其实是：

```js
<Route>
  <TrackPageView>
    {children}
  </TrackPageView>
</Route>
```

其次是`TrackRoute`组件，这个组件需要模仿官方`Route`的所有行为，包括3种渲染形式，它的`render`返回的结构应该是：

```js
<TrackPageView>
  <Route path, render, children, component, ... />
</TrackPageView>
```

而`TrackPageView`也会再带一个`<Route>`，最后在react树上是2个`<Route>`套一起，这是正常现象

所以`TrackRoute`组件的逻辑很简单，套一层`<TrackPageView>`，自己的`props`全部给`Route`

最后我们要有`trackPageView`高阶组件，它的作用是接收任何的组件，最后返回：

```js
<TrackPageView>
  <ComponentIn ... />
</TarckPageView>
```

从这一点来看，`TrackRoute = trackPageView(Route)`，似乎是这样的。

所以实际上，我们要实现`TrackPageView`和`trackPageView`，再用上面这行代码直接搞出来`TrackRoute`，即`TrackRoute`其实是没啥代码的

2018-06-21 08:59 UTC, otakustay requested changes

2018-06-21 08:59 UTC, otakustay commented on demo/components/App/index.js
> +import TrackRoute from '../../../src/components/TrackRoute';
demo最好全部从src/index下导入，这样更接近实际用的场景，有问题也能发现

2018-06-21 08:59 UTC, otakustay commented on demo/components/App/index.js
> +const TrackEventSelect = trackEvent({
看到这个使用方式我有一些进一步的想法，我们在后面的版本再看。此处其实应该能达到“label的值是实际的value”的效果，但现在看来还没到这功能

2018-06-21 08:59 UTC, otakustay commented on src/hocs/trackEvent.js
> +const getChildren = (ComponentIn, props) => {
这个if分支应该是不需要的，只管`<ComponentIn {...props} />`就可以

2018-06-21 09:55 UTC, hy-pillow commented on demo/components/App/index.js
> +const TrackEventSelect = trackEvent({
嗯，确实在lable赋值的时候也想到了，后面把这个补上

2018-06-21 10:45 UTC, otakustay approved these changes

2018-06-21 10:46 UTC, merged