Support nesting tracker(fix #4)
otakustay/react-track pull request #6
Opened 2018-09-28 13:19 UTC by hunter2009

支持嵌套TrackEvent

2018-09-28 13:32 UTC, otakustay requested changes

2018-09-28 13:32 UTC, otakustay commented on src/components/TrackEvent.js
> +        return Children.map(children, child => cloneElement(child, {...child.props, [eventPropName]: trackedCallback}));
1. 这里的`child.props`是没用的，`cloneElement`本身就有这效果
2. 这个修改除了支持多children外在功能上没有任何改变，你移除掉此处的修改，在demo中的效果一样会生效，同时具备click和change的日志

这个问题是`trackEvent`这个HOC是会透传props的，但`TrackEvent`这个组件并不会，所以连续套几个`trackEvent`和一层层嵌套`<TrackEvent>`的效果是不同的，我们要让它们等效

可以在`App/index.js`中这样尝试：

```jsx
const NavItem = ({name, to}) => (
    <TrackEvent eventPropName="onMouseEnter" category="navigation" action="enter" label={name}>
        <TrackEvent eventPropName="onMouseLeave" category="navigation" action="leave" label={name}>
            <li>
                <NavLink exact to={to} activeClassName="nav-link-active">{name}</NavLink>
            </li>
        </TrackEvent>
    </TrackEvent>
);
```

2018-09-28 13:32 UTC, otakustay commented on demo/components/App/index.js
> +const TrackSelectEventSelect = trackEvent({
此处用recompose试一步，确保是正常的

2018-09-28 13:32 UTC, otakustay commented on demo/components/Select/index.js
> +            <select value={this.state.value} onChange={this.handleChange} onClick={this.handleClick} >
从这个库的目标来说，应该不需要额外添加一个`onClick`属性才能生效。如果这个是必须的，我们的实现有问题

2018-09-28 14:09 UTC, hunter2009 commented on demo/components/Select/index.js
> +            <select value={this.state.value} onChange={this.handleChange} onClick={this.handleClick} >
每个TrackEvent会对应一个事件，所以这里面新增一个事件是为了方便调试，这处更改应该是需要的

2018-09-29 03:08 UTC, hunter2009 reviewed
本地误操作了，强制覆盖了代码，需要重新review

2018-09-29 03:57 UTC, otakustay commented
这个修改后，`trackEvent`这个HOC里的透传应该就不需要了，相应的一起改一下吧

2018-09-29 10:52 UTC, merged